name: Lint and Test

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint and Test Go Code
    runs-on:
      - ubuntu-latest
    env:
      GOPRIVATE: github.com/gateway-fm/generic-rpc
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PROXY_PIPELINES_GITHUB_TOKEN }}
        run: git config --global url."https://oauth2:${TOKEN}@github.com/gateway-fm".insteadOf "https://github.com/gateway-fm"

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.*" # The Go version to download (if necessary) and use.
      - run: |
          go version
          go clean -modcache
          go mod tidy

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

      - name: Test
        run: go test ./...

      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0